/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AadhaarVerification service. Represents a row in the &quot;Safe_Sail_AadhaarVerification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.AadhaarVerificationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.AadhaarVerificationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AadhaarVerification
 * @generated
 */
@ProviderType
public interface AadhaarVerificationModel
	extends BaseModel<AadhaarVerification> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a aadhaar verification model instance should use the {@link AadhaarVerification} interface instead.
	 */

	/**
	 * Returns the primary key of this aadhaar verification.
	 *
	 * @return the primary key of this aadhaar verification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this aadhaar verification.
	 *
	 * @param primaryKey the primary key of this aadhaar verification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the aadhaar ID of this aadhaar verification.
	 *
	 * @return the aadhaar ID of this aadhaar verification
	 */
	public long getAadhaarId();

	/**
	 * Sets the aadhaar ID of this aadhaar verification.
	 *
	 * @param aadhaarId the aadhaar ID of this aadhaar verification
	 */
	public void setAadhaarId(long aadhaarId);

	/**
	 * Returns the aadhaar user name of this aadhaar verification.
	 *
	 * @return the aadhaar user name of this aadhaar verification
	 */
	@AutoEscape
	public String getAadhaarUserName();

	/**
	 * Sets the aadhaar user name of this aadhaar verification.
	 *
	 * @param aadhaarUserName the aadhaar user name of this aadhaar verification
	 */
	public void setAadhaarUserName(String aadhaarUserName);

	/**
	 * Returns the aadhaar number of this aadhaar verification.
	 *
	 * @return the aadhaar number of this aadhaar verification
	 */
	@AutoEscape
	public String getAadhaarNumber();

	/**
	 * Sets the aadhaar number of this aadhaar verification.
	 *
	 * @param aadhaarNumber the aadhaar number of this aadhaar verification
	 */
	public void setAadhaarNumber(String aadhaarNumber);

	@Override
	public AadhaarVerification cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}