/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LifeInsurance service. Represents a row in the &quot;Safe_Sail_LifeInsurance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.LifeInsuranceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.LifeInsuranceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LifeInsurance
 * @generated
 */
@ProviderType
public interface LifeInsuranceModel extends BaseModel<LifeInsurance> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a life insurance model instance should use the {@link LifeInsurance} interface instead.
	 */

	/**
	 * Returns the primary key of this life insurance.
	 *
	 * @return the primary key of this life insurance
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this life insurance.
	 *
	 * @param primaryKey the primary key of this life insurance
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this life insurance.
	 *
	 * @return the uuid of this life insurance
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this life insurance.
	 *
	 * @param uuid the uuid of this life insurance
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the quote ID of this life insurance.
	 *
	 * @return the quote ID of this life insurance
	 */
	@AutoEscape
	public String getQuoteId();

	/**
	 * Sets the quote ID of this life insurance.
	 *
	 * @param quoteId the quote ID of this life insurance
	 */
	public void setQuoteId(String quoteId);

	/**
	 * Returns the fullname of this life insurance.
	 *
	 * @return the fullname of this life insurance
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this life insurance.
	 *
	 * @param fullname the fullname of this life insurance
	 */
	public void setFullname(String fullname);

	/**
	 * Returns the dob of this life insurance.
	 *
	 * @return the dob of this life insurance
	 */
	public Date getDob();

	/**
	 * Sets the dob of this life insurance.
	 *
	 * @param dob the dob of this life insurance
	 */
	public void setDob(Date dob);

	/**
	 * Returns the gender of this life insurance.
	 *
	 * @return the gender of this life insurance
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this life insurance.
	 *
	 * @param gender the gender of this life insurance
	 */
	public void setGender(String gender);

	/**
	 * Returns the phone no of this life insurance.
	 *
	 * @return the phone no of this life insurance
	 */
	public long getPhoneNo();

	/**
	 * Sets the phone no of this life insurance.
	 *
	 * @param phoneNo the phone no of this life insurance
	 */
	public void setPhoneNo(long phoneNo);

	/**
	 * Returns the email address of this life insurance.
	 *
	 * @return the email address of this life insurance
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this life insurance.
	 *
	 * @param emailAddress the email address of this life insurance
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the aadhar number of this life insurance.
	 *
	 * @return the aadhar number of this life insurance
	 */
	@AutoEscape
	public String getAadharNumber();

	/**
	 * Sets the aadhar number of this life insurance.
	 *
	 * @param aadharNumber the aadhar number of this life insurance
	 */
	public void setAadharNumber(String aadharNumber);

	/**
	 * Returns the pan number of this life insurance.
	 *
	 * @return the pan number of this life insurance
	 */
	@AutoEscape
	public String getPanNumber();

	/**
	 * Sets the pan number of this life insurance.
	 *
	 * @param panNumber the pan number of this life insurance
	 */
	public void setPanNumber(String panNumber);

	/**
	 * Returns the annual income of this life insurance.
	 *
	 * @return the annual income of this life insurance
	 */
	@AutoEscape
	public String getAnnualIncome();

	/**
	 * Sets the annual income of this life insurance.
	 *
	 * @param annualIncome the annual income of this life insurance
	 */
	public void setAnnualIncome(String annualIncome);

	/**
	 * Returns the sum assured of this life insurance.
	 *
	 * @return the sum assured of this life insurance
	 */
	public long getSumAssured();

	/**
	 * Sets the sum assured of this life insurance.
	 *
	 * @param sumAssured the sum assured of this life insurance
	 */
	public void setSumAssured(long sumAssured);

	/**
	 * Returns the policy term of this life insurance.
	 *
	 * @return the policy term of this life insurance
	 */
	public int getPolicyTerm();

	/**
	 * Sets the policy term of this life insurance.
	 *
	 * @param policyTerm the policy term of this life insurance
	 */
	public void setPolicyTerm(int policyTerm);

	/**
	 * Returns the pp term of this life insurance.
	 *
	 * @return the pp term of this life insurance
	 */
	public int getPPTerm();

	/**
	 * Sets the pp term of this life insurance.
	 *
	 * @param PPTerm the pp term of this life insurance
	 */
	public void setPPTerm(int PPTerm);

	/**
	 * Returns the payment frequency of this life insurance.
	 *
	 * @return the payment frequency of this life insurance
	 */
	@AutoEscape
	public String getPaymentFrequency();

	/**
	 * Sets the payment frequency of this life insurance.
	 *
	 * @param paymentFrequency the payment frequency of this life insurance
	 */
	public void setPaymentFrequency(String paymentFrequency);

	/**
	 * Returns the payout option of this life insurance.
	 *
	 * @return the payout option of this life insurance
	 */
	@AutoEscape
	public String getPayoutOption();

	/**
	 * Sets the payout option of this life insurance.
	 *
	 * @param PayoutOption the payout option of this life insurance
	 */
	public void setPayoutOption(String PayoutOption);

	/**
	 * Returns the life secure of this life insurance.
	 *
	 * @return the life secure of this life insurance
	 */
	public int getLifeSecure();

	/**
	 * Sets the life secure of this life insurance.
	 *
	 * @param lifeSecure the life secure of this life insurance
	 */
	public void setLifeSecure(int lifeSecure);

	/**
	 * Returns the life plus of this life insurance.
	 *
	 * @return the life plus of this life insurance
	 */
	public int getLifePlus();

	/**
	 * Sets the life plus of this life insurance.
	 *
	 * @param lifePlus the life plus of this life insurance
	 */
	public void setLifePlus(int lifePlus);

	/**
	 * Returns the cip benefit of this life insurance.
	 *
	 * @return the cip benefit of this life insurance
	 */
	public int getCIPBenefit();

	/**
	 * Sets the cip benefit of this life insurance.
	 *
	 * @param CIPBenefit the cip benefit of this life insurance
	 */
	public void setCIPBenefit(int CIPBenefit);

	/**
	 * Returns the add on benefits of this life insurance.
	 *
	 * @return the add on benefits of this life insurance
	 */
	@AutoEscape
	public String getAddOnBenefits();

	/**
	 * Sets the add on benefits of this life insurance.
	 *
	 * @param addOnBenefits the add on benefits of this life insurance
	 */
	public void setAddOnBenefits(String addOnBenefits);

	/**
	 * Returns the total values of this life insurance.
	 *
	 * @return the total values of this life insurance
	 */
	public long getTotalValues();

	/**
	 * Sets the total values of this life insurance.
	 *
	 * @param totalValues the total values of this life insurance
	 */
	public void setTotalValues(long totalValues);

	/**
	 * Returns the total addon of this life insurance.
	 *
	 * @return the total addon of this life insurance
	 */
	public long getTotalAddon();

	/**
	 * Sets the total addon of this life insurance.
	 *
	 * @param totalAddon the total addon of this life insurance
	 */
	public void setTotalAddon(long totalAddon);

	/**
	 * Returns the agreement of this life insurance.
	 *
	 * @return the agreement of this life insurance
	 */
	public Boolean getAgreement();

	/**
	 * Sets the agreement of this life insurance.
	 *
	 * @param agreement the agreement of this life insurance
	 */
	public void setAgreement(Boolean agreement);

	/**
	 * Returns the user ID of this life insurance.
	 *
	 * @return the user ID of this life insurance
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this life insurance.
	 *
	 * @param userId the user ID of this life insurance
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this life insurance.
	 *
	 * @return the user uuid of this life insurance
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this life insurance.
	 *
	 * @param userUuid the user uuid of this life insurance
	 */
	public void setUserUuid(String userUuid);

	@Override
	public LifeInsurance cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}