/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PanCardVerification service. Represents a row in the &quot;Safe_Sail_PanCardVerification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.PanCardVerificationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.PanCardVerificationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PanCardVerification
 * @generated
 */
@ProviderType
public interface PanCardVerificationModel
	extends BaseModel<PanCardVerification> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pan card verification model instance should use the {@link PanCardVerification} interface instead.
	 */

	/**
	 * Returns the primary key of this pan card verification.
	 *
	 * @return the primary key of this pan card verification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pan card verification.
	 *
	 * @param primaryKey the primary key of this pan card verification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pan ID of this pan card verification.
	 *
	 * @return the pan ID of this pan card verification
	 */
	public long getPanId();

	/**
	 * Sets the pan ID of this pan card verification.
	 *
	 * @param panId the pan ID of this pan card verification
	 */
	public void setPanId(long panId);

	/**
	 * Returns the pan user name of this pan card verification.
	 *
	 * @return the pan user name of this pan card verification
	 */
	@AutoEscape
	public String getPanUserName();

	/**
	 * Sets the pan user name of this pan card verification.
	 *
	 * @param panUserName the pan user name of this pan card verification
	 */
	public void setPanUserName(String panUserName);

	/**
	 * Returns the pan number of this pan card verification.
	 *
	 * @return the pan number of this pan card verification
	 */
	@AutoEscape
	public String getPanNumber();

	/**
	 * Sets the pan number of this pan card verification.
	 *
	 * @param panNumber the pan number of this pan card verification
	 */
	public void setPanNumber(String panNumber);

	@Override
	public PanCardVerification cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}