/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.safesail.service.persistence.PolicyPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Policy service. Represents a row in the &quot;Safe_Sail_Policy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.PolicyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.PolicyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Policy
 * @generated
 */
@ProviderType
public interface PolicyModel extends BaseModel<Policy> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a policy model instance should use the {@link Policy} interface instead.
	 */

	/**
	 * Returns the primary key of this policy.
	 *
	 * @return the primary key of this policy
	 */
	public PolicyPK getPrimaryKey();

	/**
	 * Sets the primary key of this policy.
	 *
	 * @param primaryKey the primary key of this policy
	 */
	public void setPrimaryKey(PolicyPK primaryKey);

	/**
	 * Returns the uuid of this policy.
	 *
	 * @return the uuid of this policy
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this policy.
	 *
	 * @param uuid the uuid of this policy
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the booking ID of this policy.
	 *
	 * @return the booking ID of this policy
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this policy.
	 *
	 * @param bookingId the booking ID of this policy
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the application number of this policy.
	 *
	 * @return the application number of this policy
	 */
	public long getApplicationNumber();

	/**
	 * Sets the application number of this policy.
	 *
	 * @param applicationNumber the application number of this policy
	 */
	public void setApplicationNumber(long applicationNumber);

	/**
	 * Returns the user ID of this policy.
	 *
	 * @return the user ID of this policy
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this policy.
	 *
	 * @param userId the user ID of this policy
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this policy.
	 *
	 * @return the user uuid of this policy
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this policy.
	 *
	 * @param userUuid the user uuid of this policy
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the full name of this policy.
	 *
	 * @return the full name of this policy
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this policy.
	 *
	 * @param fullName the full name of this policy
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the plan name of this policy.
	 *
	 * @return the plan name of this policy
	 */
	@AutoEscape
	public String getPlanName();

	/**
	 * Sets the plan name of this policy.
	 *
	 * @param planName the plan name of this policy
	 */
	public void setPlanName(String planName);

	/**
	 * Returns the annual income of this policy.
	 *
	 * @return the annual income of this policy
	 */
	@AutoEscape
	public String getAnnualIncome();

	/**
	 * Sets the annual income of this policy.
	 *
	 * @param annualIncome the annual income of this policy
	 */
	public void setAnnualIncome(String annualIncome);

	/**
	 * Returns the booking date of this policy.
	 *
	 * @return the booking date of this policy
	 */
	public Date getBookingDate();

	/**
	 * Sets the booking date of this policy.
	 *
	 * @param bookingDate the booking date of this policy
	 */
	public void setBookingDate(Date bookingDate);

	/**
	 * Returns the sum assured of this policy.
	 *
	 * @return the sum assured of this policy
	 */
	public long getSumAssured();

	/**
	 * Sets the sum assured of this policy.
	 *
	 * @param sumAssured the sum assured of this policy
	 */
	public void setSumAssured(long sumAssured);

	/**
	 * Returns the policy term of this policy.
	 *
	 * @return the policy term of this policy
	 */
	public int getPolicyTerm();

	/**
	 * Sets the policy term of this policy.
	 *
	 * @param policyTerm the policy term of this policy
	 */
	public void setPolicyTerm(int policyTerm);

	/**
	 * Returns the maturity date of this policy.
	 *
	 * @return the maturity date of this policy
	 */
	public Date getMaturityDate();

	/**
	 * Sets the maturity date of this policy.
	 *
	 * @param maturityDate the maturity date of this policy
	 */
	public void setMaturityDate(Date maturityDate);

	/**
	 * Returns the payment frequency of this policy.
	 *
	 * @return the payment frequency of this policy
	 */
	@AutoEscape
	public String getPaymentFrequency();

	/**
	 * Sets the payment frequency of this policy.
	 *
	 * @param paymentFrequency the payment frequency of this policy
	 */
	public void setPaymentFrequency(String paymentFrequency);

	/**
	 * Returns the total premium of this policy.
	 *
	 * @return the total premium of this policy
	 */
	public long getTotalPremium();

	/**
	 * Sets the total premium of this policy.
	 *
	 * @param totalPremium the total premium of this policy
	 */
	public void setTotalPremium(long totalPremium);

	/**
	 * Returns the total addon of this policy.
	 *
	 * @return the total addon of this policy
	 */
	public long getTotalAddon();

	/**
	 * Sets the total addon of this policy.
	 *
	 * @param totalAddon the total addon of this policy
	 */
	public void setTotalAddon(long totalAddon);

	/**
	 * Returns the status of this policy.
	 *
	 * @return the status of this policy
	 */
	public int getStatus();

	/**
	 * Sets the status of this policy.
	 *
	 * @param status the status of this policy
	 */
	public void setStatus(int status);

	/**
	 * Returns the quote ID of this policy.
	 *
	 * @return the quote ID of this policy
	 */
	@AutoEscape
	public String getQuoteId();

	/**
	 * Sets the quote ID of this policy.
	 *
	 * @param quoteId the quote ID of this policy
	 */
	public void setQuoteId(String quoteId);

	@Override
	public Policy cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}