/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductTable service. Represents a row in the &quot;Safe_Sail_ProductTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.ProductTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.ProductTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductTable
 * @generated
 */
@ProviderType
public interface ProductTableModel extends BaseModel<ProductTable> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product table model instance should use the {@link ProductTable} interface instead.
	 */

	/**
	 * Returns the primary key of this product table.
	 *
	 * @return the primary key of this product table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product table.
	 *
	 * @param primaryKey the primary key of this product table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product table.
	 *
	 * @return the uuid of this product table
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this product table.
	 *
	 * @param uuid the uuid of this product table
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the product ID of this product table.
	 *
	 * @return the product ID of this product table
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product table.
	 *
	 * @param productId the product ID of this product table
	 */
	public void setProductId(long productId);

	/**
	 * Returns the product name of this product table.
	 *
	 * @return the product name of this product table
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product table.
	 *
	 * @param productName the product name of this product table
	 */
	public void setProductName(String productName);

	/**
	 * Returns the premium discount of this product table.
	 *
	 * @return the premium discount of this product table
	 */
	public int getPremiumDiscount();

	/**
	 * Sets the premium discount of this product table.
	 *
	 * @param premiumDiscount the premium discount of this product table
	 */
	public void setPremiumDiscount(int premiumDiscount);

	/**
	 * Returns the total discount of this product table.
	 *
	 * @return the total discount of this product table
	 */
	public int getTotalDiscount();

	/**
	 * Sets the total discount of this product table.
	 *
	 * @param totalDiscount the total discount of this product table
	 */
	public void setTotalDiscount(int totalDiscount);

	/**
	 * Returns the year pay of this product table.
	 *
	 * @return the year pay of this product table
	 */
	public long getYearPay();

	/**
	 * Sets the year pay of this product table.
	 *
	 * @param yearPay the year pay of this product table
	 */
	public void setYearPay(long yearPay);

	/**
	 * Returns the month pay of this product table.
	 *
	 * @return the month pay of this product table
	 */
	public long getMonthPay();

	/**
	 * Sets the month pay of this product table.
	 *
	 * @param monthPay the month pay of this product table
	 */
	public void setMonthPay(long monthPay);

	/**
	 * Returns the total premium of this product table.
	 *
	 * @return the total premium of this product table
	 */
	public long getTotalPremium();

	/**
	 * Sets the total premium of this product table.
	 *
	 * @param totalPremium the total premium of this product table
	 */
	public void setTotalPremium(long totalPremium);

	@Override
	public ProductTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}