/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserTable service. Represents a row in the &quot;Safe_Sail_UserTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.safesail.model.impl.UserTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.safesail.model.impl.UserTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserTable
 * @generated
 */
@ProviderType
public interface UserTableModel extends BaseModel<UserTable> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user table model instance should use the {@link UserTable} interface instead.
	 */

	/**
	 * Returns the primary key of this user table.
	 *
	 * @return the primary key of this user table
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this user table.
	 *
	 * @param primaryKey the primary key of this user table
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this user table.
	 *
	 * @return the uuid of this user table
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user table.
	 *
	 * @param uuid the uuid of this user table
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the quote ID of this user table.
	 *
	 * @return the quote ID of this user table
	 */
	@AutoEscape
	public String getQuoteId();

	/**
	 * Sets the quote ID of this user table.
	 *
	 * @param quoteId the quote ID of this user table
	 */
	public void setQuoteId(String quoteId);

	/**
	 * Returns the user ID of this user table.
	 *
	 * @return the user ID of this user table
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user table.
	 *
	 * @param userId the user ID of this user table
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user table.
	 *
	 * @return the user uuid of this user table
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user table.
	 *
	 * @param userUuid the user uuid of this user table
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user type of this user table.
	 *
	 * @return the user type of this user table
	 */
	@AutoEscape
	public String getUserType();

	/**
	 * Sets the user type of this user table.
	 *
	 * @param userType the user type of this user table
	 */
	public void setUserType(String userType);

	@Override
	public UserTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}