/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.safesail.model.addOnFieldData;
import com.safesail.model.addOnFieldDataModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the addOnFieldData service. Represents a row in the &quot;Safe_Sail_addOnFieldData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>addOnFieldDataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link addOnFieldDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see addOnFieldDataImpl
 * @generated
 */
@JSON(strict = true)
public class addOnFieldDataModelImpl
	extends BaseModelImpl<addOnFieldData> implements addOnFieldDataModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a add on field data model instance should use the <code>addOnFieldData</code> interface instead.
	 */
	public static final String TABLE_NAME = "Safe_Sail_addOnFieldData";

	public static final Object[][] TABLE_COLUMNS = {
		{"addonId", Types.BIGINT}, {"addonName", Types.VARCHAR},
		{"addonValue", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("addonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("addonName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addonValue", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Safe_Sail_addOnFieldData (addonId LONG not null primary key,addonName VARCHAR(75) null,addonValue VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Safe_Sail_addOnFieldData";

	public static final String ORDER_BY_JPQL =
		" ORDER BY addOnFieldData.addonId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Safe_Sail_addOnFieldData.addonId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADDONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public addOnFieldDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _addonId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAddonId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _addonId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return addOnFieldData.class;
	}

	@Override
	public String getModelClassName() {
		return addOnFieldData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<addOnFieldData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<addOnFieldData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<addOnFieldData, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((addOnFieldData)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<addOnFieldData, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<addOnFieldData, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(addOnFieldData)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<addOnFieldData, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<addOnFieldData, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<addOnFieldData, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<addOnFieldData, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<addOnFieldData, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<addOnFieldData, Object>>();
		Map<String, BiConsumer<addOnFieldData, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<addOnFieldData, ?>>();

		attributeGetterFunctions.put("addonId", addOnFieldData::getAddonId);
		attributeSetterBiConsumers.put(
			"addonId",
			(BiConsumer<addOnFieldData, Long>)addOnFieldData::setAddonId);
		attributeGetterFunctions.put("addonName", addOnFieldData::getAddonName);
		attributeSetterBiConsumers.put(
			"addonName",
			(BiConsumer<addOnFieldData, String>)addOnFieldData::setAddonName);
		attributeGetterFunctions.put(
			"addonValue", addOnFieldData::getAddonValue);
		attributeSetterBiConsumers.put(
			"addonValue",
			(BiConsumer<addOnFieldData, String>)addOnFieldData::setAddonValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAddonId() {
		return _addonId;
	}

	@Override
	public void setAddonId(long addonId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addonId = addonId;
	}

	@JSON
	@Override
	public String getAddonName() {
		if (_addonName == null) {
			return "";
		}
		else {
			return _addonName;
		}
	}

	@Override
	public void setAddonName(String addonName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addonName = addonName;
	}

	@JSON
	@Override
	public String getAddonValue() {
		if (_addonValue == null) {
			return "";
		}
		else {
			return _addonValue;
		}
	}

	@Override
	public void setAddonValue(String addonValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addonValue = addonValue;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, addOnFieldData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public addOnFieldData toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, addOnFieldData>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		addOnFieldDataImpl addOnFieldDataImpl = new addOnFieldDataImpl();

		addOnFieldDataImpl.setAddonId(getAddonId());
		addOnFieldDataImpl.setAddonName(getAddonName());
		addOnFieldDataImpl.setAddonValue(getAddonValue());

		addOnFieldDataImpl.resetOriginalValues();

		return addOnFieldDataImpl;
	}

	@Override
	public addOnFieldData cloneWithOriginalValues() {
		addOnFieldDataImpl addOnFieldDataImpl = new addOnFieldDataImpl();

		addOnFieldDataImpl.setAddonId(
			this.<Long>getColumnOriginalValue("addonId"));
		addOnFieldDataImpl.setAddonName(
			this.<String>getColumnOriginalValue("addonName"));
		addOnFieldDataImpl.setAddonValue(
			this.<String>getColumnOriginalValue("addonValue"));

		return addOnFieldDataImpl;
	}

	@Override
	public int compareTo(addOnFieldData addOnFieldData) {
		long primaryKey = addOnFieldData.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof addOnFieldData)) {
			return false;
		}

		addOnFieldData addOnFieldData = (addOnFieldData)object;

		long primaryKey = addOnFieldData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<addOnFieldData> toCacheModel() {
		addOnFieldDataCacheModel addOnFieldDataCacheModel =
			new addOnFieldDataCacheModel();

		addOnFieldDataCacheModel.addonId = getAddonId();

		addOnFieldDataCacheModel.addonName = getAddonName();

		String addonName = addOnFieldDataCacheModel.addonName;

		if ((addonName != null) && (addonName.length() == 0)) {
			addOnFieldDataCacheModel.addonName = null;
		}

		addOnFieldDataCacheModel.addonValue = getAddonValue();

		String addonValue = addOnFieldDataCacheModel.addonValue;

		if ((addonValue != null) && (addonValue.length() == 0)) {
			addOnFieldDataCacheModel.addonValue = null;
		}

		return addOnFieldDataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<addOnFieldData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<addOnFieldData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<addOnFieldData, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((addOnFieldData)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, addOnFieldData>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					addOnFieldData.class, ModelWrapper.class);

	}

	private long _addonId;
	private String _addonName;
	private String _addonValue;

	public <T> T getColumnValue(String columnName) {
		Function<addOnFieldData, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((addOnFieldData)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("addonId", _addonId);
		_columnOriginalValues.put("addonName", _addonName);
		_columnOriginalValues.put("addonValue", _addonValue);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("addonId", 1L);

		columnBitmasks.put("addonName", 2L);

		columnBitmasks.put("addonValue", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private addOnFieldData _escapedModel;

}