/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.safesail.model.PanCardVerification;
import com.safesail.model.PanCardVerificationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PanCardVerification service. Represents a row in the &quot;Safe_Sail_PanCardVerification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PanCardVerificationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PanCardVerificationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PanCardVerificationImpl
 * @generated
 */
@JSON(strict = true)
public class PanCardVerificationModelImpl
	extends BaseModelImpl<PanCardVerification>
	implements PanCardVerificationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pan card verification model instance should use the <code>PanCardVerification</code> interface instead.
	 */
	public static final String TABLE_NAME = "Safe_Sail_PanCardVerification";

	public static final Object[][] TABLE_COLUMNS = {
		{"panId", Types.BIGINT}, {"panUserName", Types.VARCHAR},
		{"panNumber", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("panId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("panUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("panNumber", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Safe_Sail_PanCardVerification (panId LONG not null primary key,panUserName VARCHAR(75) null,panNumber VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Safe_Sail_PanCardVerification";

	public static final String ORDER_BY_JPQL =
		" ORDER BY panCardVerification.panId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Safe_Sail_PanCardVerification.panId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PANNUMBER_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PANID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PanCardVerificationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _panId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _panId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PanCardVerification.class;
	}

	@Override
	public String getModelClassName() {
		return PanCardVerification.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PanCardVerification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PanCardVerification, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PanCardVerification, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PanCardVerification)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PanCardVerification, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PanCardVerification, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PanCardVerification)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PanCardVerification, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PanCardVerification, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PanCardVerification, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PanCardVerification, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PanCardVerification, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PanCardVerification, Object>>();
		Map<String, BiConsumer<PanCardVerification, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PanCardVerification, ?>>();

		attributeGetterFunctions.put("panId", PanCardVerification::getPanId);
		attributeSetterBiConsumers.put(
			"panId",
			(BiConsumer<PanCardVerification, Long>)
				PanCardVerification::setPanId);
		attributeGetterFunctions.put(
			"panUserName", PanCardVerification::getPanUserName);
		attributeSetterBiConsumers.put(
			"panUserName",
			(BiConsumer<PanCardVerification, String>)
				PanCardVerification::setPanUserName);
		attributeGetterFunctions.put(
			"panNumber", PanCardVerification::getPanNumber);
		attributeSetterBiConsumers.put(
			"panNumber",
			(BiConsumer<PanCardVerification, String>)
				PanCardVerification::setPanNumber);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPanId() {
		return _panId;
	}

	@Override
	public void setPanId(long panId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_panId = panId;
	}

	@JSON
	@Override
	public String getPanUserName() {
		if (_panUserName == null) {
			return "";
		}
		else {
			return _panUserName;
		}
	}

	@Override
	public void setPanUserName(String panUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_panUserName = panUserName;
	}

	@JSON
	@Override
	public String getPanNumber() {
		if (_panNumber == null) {
			return "";
		}
		else {
			return _panNumber;
		}
	}

	@Override
	public void setPanNumber(String panNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_panNumber = panNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPanNumber() {
		return getColumnOriginalValue("panNumber");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PanCardVerification.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PanCardVerification toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PanCardVerification>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PanCardVerificationImpl panCardVerificationImpl =
			new PanCardVerificationImpl();

		panCardVerificationImpl.setPanId(getPanId());
		panCardVerificationImpl.setPanUserName(getPanUserName());
		panCardVerificationImpl.setPanNumber(getPanNumber());

		panCardVerificationImpl.resetOriginalValues();

		return panCardVerificationImpl;
	}

	@Override
	public PanCardVerification cloneWithOriginalValues() {
		PanCardVerificationImpl panCardVerificationImpl =
			new PanCardVerificationImpl();

		panCardVerificationImpl.setPanId(
			this.<Long>getColumnOriginalValue("panId"));
		panCardVerificationImpl.setPanUserName(
			this.<String>getColumnOriginalValue("panUserName"));
		panCardVerificationImpl.setPanNumber(
			this.<String>getColumnOriginalValue("panNumber"));

		return panCardVerificationImpl;
	}

	@Override
	public int compareTo(PanCardVerification panCardVerification) {
		long primaryKey = panCardVerification.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PanCardVerification)) {
			return false;
		}

		PanCardVerification panCardVerification = (PanCardVerification)object;

		long primaryKey = panCardVerification.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PanCardVerification> toCacheModel() {
		PanCardVerificationCacheModel panCardVerificationCacheModel =
			new PanCardVerificationCacheModel();

		panCardVerificationCacheModel.panId = getPanId();

		panCardVerificationCacheModel.panUserName = getPanUserName();

		String panUserName = panCardVerificationCacheModel.panUserName;

		if ((panUserName != null) && (panUserName.length() == 0)) {
			panCardVerificationCacheModel.panUserName = null;
		}

		panCardVerificationCacheModel.panNumber = getPanNumber();

		String panNumber = panCardVerificationCacheModel.panNumber;

		if ((panNumber != null) && (panNumber.length() == 0)) {
			panCardVerificationCacheModel.panNumber = null;
		}

		return panCardVerificationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PanCardVerification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PanCardVerification, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PanCardVerification, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PanCardVerification)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PanCardVerification>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PanCardVerification.class, ModelWrapper.class);

	}

	private long _panId;
	private String _panUserName;
	private String _panNumber;

	public <T> T getColumnValue(String columnName) {
		Function<PanCardVerification, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PanCardVerification)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("panId", _panId);
		_columnOriginalValues.put("panUserName", _panUserName);
		_columnOriginalValues.put("panNumber", _panNumber);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("panId", 1L);

		columnBitmasks.put("panUserName", 2L);

		columnBitmasks.put("panNumber", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PanCardVerification _escapedModel;

}