/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.safesail.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.safesail.model.PanCardVerification;
import com.safesail.service.PanCardVerificationLocalService;
import com.safesail.service.PanCardVerificationLocalServiceUtil;
import com.safesail.service.persistence.AadhaarVerificationPersistence;
import com.safesail.service.persistence.FieldConfigurationPersistence;
import com.safesail.service.persistence.LifeInsurancePersistence;
import com.safesail.service.persistence.PanCardVerificationPersistence;
import com.safesail.service.persistence.PolicyPersistence;
import com.safesail.service.persistence.ProductTablePersistence;
import com.safesail.service.persistence.UserTablePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the pan card verification local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.safesail.service.impl.PanCardVerificationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.safesail.service.impl.PanCardVerificationLocalServiceImpl
 * @generated
 */
public abstract class PanCardVerificationLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   PanCardVerificationLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PanCardVerificationLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PanCardVerificationLocalServiceUtil</code>.
	 */

	/**
	 * Adds the pan card verification to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PanCardVerificationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param panCardVerification the pan card verification
	 * @return the pan card verification that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PanCardVerification addPanCardVerification(
		PanCardVerification panCardVerification) {

		panCardVerification.setNew(true);

		return panCardVerificationPersistence.update(panCardVerification);
	}

	/**
	 * Creates a new pan card verification with the primary key. Does not add the pan card verification to the database.
	 *
	 * @param panId the primary key for the new pan card verification
	 * @return the new pan card verification
	 */
	@Override
	@Transactional(enabled = false)
	public PanCardVerification createPanCardVerification(long panId) {
		return panCardVerificationPersistence.create(panId);
	}

	/**
	 * Deletes the pan card verification with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PanCardVerificationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param panId the primary key of the pan card verification
	 * @return the pan card verification that was removed
	 * @throws PortalException if a pan card verification with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PanCardVerification deletePanCardVerification(long panId)
		throws PortalException {

		return panCardVerificationPersistence.remove(panId);
	}

	/**
	 * Deletes the pan card verification from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PanCardVerificationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param panCardVerification the pan card verification
	 * @return the pan card verification that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PanCardVerification deletePanCardVerification(
		PanCardVerification panCardVerification) {

		return panCardVerificationPersistence.remove(panCardVerification);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return panCardVerificationPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PanCardVerification.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return panCardVerificationPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.safesail.model.impl.PanCardVerificationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return panCardVerificationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.safesail.model.impl.PanCardVerificationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return panCardVerificationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return panCardVerificationPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return panCardVerificationPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PanCardVerification fetchPanCardVerification(long panId) {
		return panCardVerificationPersistence.fetchByPrimaryKey(panId);
	}

	/**
	 * Returns the pan card verification with the primary key.
	 *
	 * @param panId the primary key of the pan card verification
	 * @return the pan card verification
	 * @throws PortalException if a pan card verification with the primary key could not be found
	 */
	@Override
	public PanCardVerification getPanCardVerification(long panId)
		throws PortalException {

		return panCardVerificationPersistence.findByPrimaryKey(panId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			panCardVerificationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PanCardVerification.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("panId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			panCardVerificationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			PanCardVerification.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("panId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			panCardVerificationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PanCardVerification.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("panId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return panCardVerificationPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement PanCardVerificationLocalServiceImpl#deletePanCardVerification(PanCardVerification) to avoid orphaned data");
		}

		return panCardVerificationLocalService.deletePanCardVerification(
			(PanCardVerification)persistedModel);
	}

	@Override
	public BasePersistence<PanCardVerification> getBasePersistence() {
		return panCardVerificationPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return panCardVerificationPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the pan card verifications.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.safesail.model.impl.PanCardVerificationModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of pan card verifications
	 * @param end the upper bound of the range of pan card verifications (not inclusive)
	 * @return the range of pan card verifications
	 */
	@Override
	public List<PanCardVerification> getPanCardVerifications(
		int start, int end) {

		return panCardVerificationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of pan card verifications.
	 *
	 * @return the number of pan card verifications
	 */
	@Override
	public int getPanCardVerificationsCount() {
		return panCardVerificationPersistence.countAll();
	}

	/**
	 * Updates the pan card verification in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PanCardVerificationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param panCardVerification the pan card verification
	 * @return the pan card verification that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PanCardVerification updatePanCardVerification(
		PanCardVerification panCardVerification) {

		return panCardVerificationPersistence.update(panCardVerification);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PanCardVerificationLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		panCardVerificationLocalService =
			(PanCardVerificationLocalService)aopProxy;

		_setLocalServiceUtilService(panCardVerificationLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PanCardVerificationLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PanCardVerification.class;
	}

	protected String getModelClassName() {
		return PanCardVerification.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				panCardVerificationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		PanCardVerificationLocalService panCardVerificationLocalService) {

		try {
			Field field =
				PanCardVerificationLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, panCardVerificationLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AadhaarVerificationPersistence aadhaarVerificationPersistence;

	@Reference
	protected FieldConfigurationPersistence fieldConfigurationPersistence;

	@Reference
	protected LifeInsurancePersistence lifeInsurancePersistence;

	protected PanCardVerificationLocalService panCardVerificationLocalService;

	@Reference
	protected PanCardVerificationPersistence panCardVerificationPersistence;

	@Reference
	protected PolicyPersistence policyPersistence;

	@Reference
	protected ProductTablePersistence productTablePersistence;

	@Reference
	protected UserTablePersistence userTablePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		PanCardVerificationLocalServiceBaseImpl.class);

}